""" 
 Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

def findTheDifference(s,t):
	"""
	XOR
	"""
	result=0
	for ch in s+t:
		result ^= ord(ch)
	return chr(result)

def findTheDifference2(s,t):
	"""
	hash table
	"""
	dic={}
	for ch in s:
		if ch not in dic:
			dic[ch]=1
		else:
			dic[ch]+=1
	for ch in t:
		if dic.get(ch,0)==0:
			return ch
		else:
			dic[ch]-=1


